//// Code generated by protoc-gen-go. DO NOT EDIT.
//// versions:
//// 	protoc-gen-go v1.27.1
//// 	protoc        v3.19.4
//// source: msg/proto/api.proto
//
//package dto
//
//import (
//	context "context"
//	_ "google.golang.org/genproto/googleapis/api/annotations"
//	grpc "google.golang.org/grpc"
//	codes "google.golang.org/grpc/codes"
//	status "google.golang.org/grpc/status"
//	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
//	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
//	reflect "reflect"
//	sync "sync"
//)
//
//const (
//	// Verify that this generated code is sufficiently up-to-date.
//	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
//	// Verify that runtime/protoimpl is sufficiently up-to-date.
//	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
//)
//
//// 创建req
//type CreateReq struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	Id   int64            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
//	Name []string         `protobuf:"bytes,2,rep,name=name,proto3" json:"name,omitempty"`
//	Data []*CreateReq_One `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
//}
//
//func (x *CreateReq) Reset() {
//	*x = CreateReq{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_msg_proto_api_proto_msgTypes[0]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *CreateReq) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*CreateReq) ProtoMessage() {}
//
//func (x *CreateReq) ProtoReflect() protoreflect.Message {
//	mi := &file_msg_proto_api_proto_msgTypes[0]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use CreateReq.ProtoReflect.Descriptor instead.
//func (*CreateReq) Descriptor() ([]byte, []int) {
//	return file_msg_proto_api_proto_rawDescGZIP(), []int{0}
//}
//
//func (x *CreateReq) GetId() int64 {
//	if x != nil {
//		return x.Id
//	}
//	return 0
//}
//
//func (x *CreateReq) GetName() []string {
//	if x != nil {
//		return x.Name
//	}
//	return nil
//}
//
//func (x *CreateReq) GetData() []*CreateReq_One {
//	if x != nil {
//		return x.Data
//	}
//	return nil
//}
//
//// 创建resp
//type CreateResp struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
//	Desc string `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
//}
//
//func (x *CreateResp) Reset() {
//	*x = CreateResp{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_msg_proto_api_proto_msgTypes[1]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *CreateResp) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*CreateResp) ProtoMessage() {}
//
//func (x *CreateResp) ProtoReflect() protoreflect.Message {
//	mi := &file_msg_proto_api_proto_msgTypes[1]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use CreateResp.ProtoReflect.Descriptor instead.
//func (*CreateResp) Descriptor() ([]byte, []int) {
//	return file_msg_proto_api_proto_rawDescGZIP(), []int{1}
//}
//
//func (x *CreateResp) GetCode() int64 {
//	if x != nil {
//		return x.Code
//	}
//	return 0
//}
//
//func (x *CreateResp) GetDesc() string {
//	if x != nil {
//		return x.Desc
//	}
//	return ""
//}
//
//type CreateReq_One struct {
//	state         protoimpl.MessageState
//	sizeCache     protoimpl.SizeCache
//	unknownFields protoimpl.UnknownFields
//
//	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
//}
//
//func (x *CreateReq_One) Reset() {
//	*x = CreateReq_One{}
//	if protoimpl.UnsafeEnabled {
//		mi := &file_msg_proto_api_proto_msgTypes[2]
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		ms.StoreMessageInfo(mi)
//	}
//}
//
//func (x *CreateReq_One) String() string {
//	return protoimpl.X.MessageStringOf(x)
//}
//
//func (*CreateReq_One) ProtoMessage() {}
//
//func (x *CreateReq_One) ProtoReflect() protoreflect.Message {
//	mi := &file_msg_proto_api_proto_msgTypes[2]
//	if protoimpl.UnsafeEnabled && x != nil {
//		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
//		if ms.LoadMessageInfo() == nil {
//			ms.StoreMessageInfo(mi)
//		}
//		return ms
//	}
//	return mi.MessageOf(x)
//}
//
//// Deprecated: Use CreateReq_One.ProtoReflect.Descriptor instead.
//func (*CreateReq_One) Descriptor() ([]byte, []int) {
//	return file_msg_proto_api_proto_rawDescGZIP(), []int{0, 0}
//}
//
//func (x *CreateReq_One) GetId() int64 {
//	if x != nil {
//		return x.Id
//	}
//	return 0
//}
//
//var File_msg_proto_api_proto protoreflect.FileDescriptor
//
//var file_msg_proto_api_proto_rawDesc = []byte{
//	0x0a, 0x13, 0x6d, 0x73, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2e,
//	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x64, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
//	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
//	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61,
//	0x74, 0x65, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
//	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
//	0x03, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x64, 0x61, 0x74,
//	0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x64, 0x74, 0x6f, 0x2e, 0x43, 0x72,
//	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x2e, 0x4f, 0x6e, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74,
//	0x61, 0x1a, 0x15, 0x0a, 0x03, 0x4f, 0x6e, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
//	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61,
//	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
//	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65,
//	0x73, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x32, 0x54,
//	0x0a, 0x07, 0x48, 0x61, 0x70, 0x73, 0x41, 0x70, 0x69, 0x12, 0x49, 0x0a, 0x06, 0x43, 0x72, 0x65,
//	0x61, 0x74, 0x65, 0x12, 0x0e, 0x2e, 0x64, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
//	0x52, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x64, 0x74, 0x6f, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
//	0x52, 0x65, 0x73, 0x70, 0x22, 0x1e, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x18, 0x22, 0x13, 0x2f, 0x61,
//	0x70, 0x69, 0x2f, 0x76, 0x31, 0x2f, 0x68, 0x61, 0x70, 0x73, 0x2f, 0x63, 0x72, 0x65, 0x61, 0x74,
//	0x65, 0x3a, 0x01, 0x2a, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x64, 0x74, 0x6f, 0x62, 0x06, 0x70,
//	0x72, 0x6f, 0x74, 0x6f, 0x33,
//}
//
//var (
//	file_msg_proto_api_proto_rawDescOnce sync.Once
//	file_msg_proto_api_proto_rawDescData = file_msg_proto_api_proto_rawDesc
//)
//
//func file_msg_proto_api_proto_rawDescGZIP() []byte {
//	file_msg_proto_api_proto_rawDescOnce.Do(func() {
//		file_msg_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_proto_api_proto_rawDescData)
//	})
//	return file_msg_proto_api_proto_rawDescData
//}
//
//var file_msg_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
//var file_msg_proto_api_proto_goTypes = []interface{}{
//	(*CreateReq)(nil),     // 0: dto.CreateReq
//	(*CreateResp)(nil),    // 1: dto.CreateResp
//	(*CreateReq_One)(nil), // 2: dto.CreateReq.One
//}
//var file_msg_proto_api_proto_depIdxs = []int32{
//	2, // 0: dto.CreateReq.data:type_name -> dto.CreateReq.One
//	0, // 1: dto.HapsApi.Create:input_type -> dto.CreateReq
//	1, // 2: dto.HapsApi.Create:output_type -> dto.CreateResp
//	2, // [2:3] is the sub-list for method output_type
//	1, // [1:2] is the sub-list for method input_type
//	1, // [1:1] is the sub-list for extension type_name
//	1, // [1:1] is the sub-list for extension extendee
//	0, // [0:1] is the sub-list for field type_name
//}
//
//func init() { file_msg_proto_api_proto_init() }
//func file_msg_proto_api_proto_init() {
//	if File_msg_proto_api_proto != nil {
//		return
//	}
//	if !protoimpl.UnsafeEnabled {
//		file_msg_proto_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*CreateReq); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//		file_msg_proto_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*CreateResp); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//		file_msg_proto_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
//			switch v := v.(*CreateReq_One); i {
//			case 0:
//				return &v.state
//			case 1:
//				return &v.sizeCache
//			case 2:
//				return &v.unknownFields
//			default:
//				return nil
//			}
//		}
//	}
//	type x struct{}
//	out := protoimpl.TypeBuilder{
//		File: protoimpl.DescBuilder{
//			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
//			RawDescriptor: file_msg_proto_api_proto_rawDesc,
//			NumEnums:      0,
//			NumMessages:   3,
//			NumExtensions: 0,
//			NumServices:   1,
//		},
//		GoTypes:           file_msg_proto_api_proto_goTypes,
//		DependencyIndexes: file_msg_proto_api_proto_depIdxs,
//		MessageInfos:      file_msg_proto_api_proto_msgTypes,
//	}.Build()
//	File_msg_proto_api_proto = out.File
//	file_msg_proto_api_proto_rawDesc = nil
//	file_msg_proto_api_proto_goTypes = nil
//	file_msg_proto_api_proto_depIdxs = nil
//}
//
//// Reference imports to suppress errors if they are not otherwise used.
//var _ context.Context
//var _ grpc.ClientConnInterface
//
//// This is a compile-time assertion to ensure that this generated file
//// is compatible with the grpc package it is being compiled against.
//const _ = grpc.SupportPackageIsVersion6
//
//// HapsApiClient is the client API for HapsApi service.
////
//// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
//type HapsApiClient interface {
//	// 创建Haps
//	Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error)
//}
//
//type hapsApiClient struct {
//	cc grpc.ClientConnInterface
//}
//
//func NewHapsApiClient(cc grpc.ClientConnInterface) HapsApiClient {
//	return &hapsApiClient{cc}
//}
//
//func (c *hapsApiClient) Create(ctx context.Context, in *CreateReq, opts ...grpc.CallOption) (*CreateResp, error) {
//	out := new(CreateResp)
//	err := c.cc.Invoke(ctx, "/dto.HapsApi/Create", in, out, opts...)
//	if err != nil {
//		return nil, err
//	}
//	return out, nil
//}
//
//// HapsApiServer is the server API for HapsApi service.
//type HapsApiServer interface {
//	// 创建Haps
//	Create(context.Context, *CreateReq) (*CreateResp, error)
//}
//
//// UnimplementedHapsApiServer can be embedded to have forward compatible implementations.
//type UnimplementedHapsApiServer struct {
//}
//
//func (*UnimplementedHapsApiServer) Create(context.Context, *CreateReq) (*CreateResp, error) {
//	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
//}
//
//func RegisterHapsApiServer(s *grpc.Server, srv HapsApiServer) {
//	s.RegisterService(&_HapsApi_serviceDesc, srv)
//}
//
//func _HapsApi_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
//	in := new(CreateReq)
//	if err := dec(in); err != nil {
//		return nil, err
//	}
//	if interceptor == nil {
//		return srv.(HapsApiServer).Create(ctx, in)
//	}
//	info := &grpc.UnaryServerInfo{
//		Server:     srv,
//		FullMethod: "/dto.HapsApi/Create",
//	}
//	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
//		return srv.(HapsApiServer).Create(ctx, req.(*CreateReq))
//	}
//	return interceptor(ctx, in, info, handler)
//}
//
//var _HapsApi_serviceDesc = grpc.ServiceDesc{
//	ServiceName: "dto.HapsApi",
//	HandlerType: (*HapsApiServer)(nil),
//	Methods: []grpc.MethodDesc{
//		{
//			MethodName: "Create",
//			Handler:    _HapsApi_Create_Handler,
//		},
//	},
//	Streams:  []grpc.StreamDesc{},
//	Metadata: "msg/proto/api.proto",
//}
