// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package dto

import (
	gin "github.com/gin-gonic/gin"
)

// IHapsApi 是 HapsApi 的interface
type IHapsApi interface {
	// 创建Haps
	Create(ctx *gin.Context, req *CreateReq) (*CreateResp, error)
}

func RegisterHapsApi(router gin.IRouter, api IHapsApi) {
	router.POST("/api/v1/haps/create", wrapper(api.Create))
}

// 创建req
type CreateReq struct {
	Id   int64            `json:"id" form:"id"`
	Name []string         `json:"name" form:"name"`
	Data []*CreateReq_One `json:"data" form:"data"`
}

type CreateReq_One struct {
	Id Number `json:"id" form:"id"`
}

// 创建resp
type CreateResp struct {
	Code int64  `json:"code" form:"code"`
	Desc string `json:"desc" form:"desc"`
}
